[package]
distribution = "2201.0.0"

[build-options]
observabilityIncluded = true

[[platform.java11.dependency]]
artifactId = "h2"
version = "2.0.206"
groupId = "com.h2database"
modules = ["ballerina_ms_sample.customer_service"]